spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ITS?serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  flyway:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ITS?serverTimezone=UTC}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    enabled: true
    schemas: public
    locations: classpath:db/migration
